apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-{{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "mychart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Values.configMap.name }}

