apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-server-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - web-server-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: web-server-service
        port:
          number: 80

