apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-server

